networks:
  local:

services:

  postgres:
    container_name: ${COMPOSE_PROJECT_NAME}_postgres
    user: ${UID}:${GID}
    image: postgres:17-alpine
    restart: unless-stopped
    volumes:
      - /etc/passwd:/etc/passwd:ro # change users for db initialization
      - ./data/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_DATABASE}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      # life hack. In this case postgres create subdirectory for files, which created from container and non root user
      - PGDATA=/var/lib/postgresql/data/_data
    ports:
      - "${DB_PORT_EXTERNAL}:5432"
    networks:
      - local

  php: &app
    container_name: ${COMPOSE_PROJECT_NAME}_php
    user: ${UID}:${GID}
    build:
      context: ./php
      dockerfile: ./Dockerfile
    expose:
      - 9000
    restart: unless-stopped
    depends_on:
      - postgres
    volumes:
      - ${PROJECT_ROOT}:/var/www
      - ./php/php.ini:/usr/local/etc/php/php.ini
    environment:
      - MC_PROFILE_ROOT:/tmp
    networks:
      - local

  nginx:
    container_name: ${COMPOSE_PROJECT_NAME}_nginx
    image: nginx:alpine
    restart: unless-stopped
    depends_on:
      - php
    ports:
      - ${NGINX_PORT_EXTERNAL}:80
    volumes:
      - ${PROJECT_ROOT}:/var/www
      - ./nginx/local.conf:/etc/nginx/conf.d/default.conf
      - ./data/nginx/logs:/var/log/nginx
    networks:
      - local
